server:
  port: 8082

spring:
  application:
    name: machines
  security:
    user:
      name: user
      password: password
  datasource:
    url: jdbc:postgresql://localhost:5432/worksite-db
    username: worksite-user
    password: worksite-pass
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
